language: python
sudo: false
python:
- 3.8
- 3.7
- 3.6
- 3.5
- 2.7
before_install:
- pip install codecov tox>=1.8
install:
- if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PYVER=py27; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PYVER=py35; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PYVER=py36; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PYVER=py37; fi
- if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then export PYVER=py38; fi
script: COMMAND='coverage run' tox -e$PYVER
after_success:
- codecov
